-- 010 · 2026-09 article set (generated by scripts/content/build-news-seed.mjs
-- from content/news/*.md — do not edit by hand; edit the Markdown and re-run).
--
-- Rows are upserted by slug: seven new articles plus the 2026 annual general
-- meeting report, which replaces the earlier translation with the council's
-- own full-text article and its photographs. Article photographs ship with
-- the site under public/news-media/<slug>/ and are referenced with a leading
-- slash, so no Storage upload is required.
--
-- Applied to the remote project on 2026-09-10 (launch), after
-- 20260902120000 → 121000 → 122000 (the five first-level categories must
-- exist before the category sub-selects run). Article bodies are edited in
-- the CMS from here on; re-running this seed would overwrite those edits.

-- beijing-poly-art-cultural-cooperation (source: docs/support docs/V2/新闻提炼(1).docx)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'beijing-poly-art-cultural-cooperation',
  (select id from public.news_categories where slug = 'association-news'),
  $obci$大洋洲工商业委员会与保利艺术教育共商中澳人文艺术合作 拟共同策划2026年悉尼春节联欢晚会$obci$, $obci$Oceania Business Council and Poly Art Education Discuss China-Australia Cultural and Arts Cooperation, Plan to Jointly Organise 2026 Sydney Spring Festival Gala$obci$,
  $obci$2025年12月11日，大洋洲工商业委员会执行会长孙国照在北京保利艺术博物馆与保利艺术教育投资有限公司总经理陈鹏、副总经理解瑞会谈，双方就共同策划2026年澳大利亚悉尼春节联欢晚会达成共识，并计划在墨尔本拓展艺术展览、教育研学及青少年交流合作。$obci$, $obci$On 11 December 2025, Oceania Business Council Executive President Sunny Sun met Poly Art Education Investment Co., Ltd. General Manager Chen Peng and Deputy General Manager Xie Rui at the Poly Art Museum in Beijing. The two sides agreed to jointly plan the 2026 Sydney Spring Festival Gala and to expand arts, education and youth exchange cooperation in Melbourne.$obci$,
  $obci$2025年12月11日，大洋洲工商业委员会执行会长孙国照在北京保利艺术博物馆与保利艺术教育投资有限公司总经理陈鹏、副总经理解瑞举行会谈。

双方围绕深化中澳人文艺术合作展开深入交流，并达成多项共识。核心议题是共同策划打造2026年澳大利亚悉尼春节联欢晚会，旨在将其发展为促进中澳文化互鉴的高水平品牌活动。此外，双方计划未来在墨尔本拓展艺术展览、教育研学及青少年交流等多形式合作，构建常态化文化交流网络。

此次会晤标志着双方在人文艺术领域的务实合作迈出关键一步，为未来系列文化项目的推进奠定了坚实基础。$obci$,
  $obci$On 11 December 2025, Oceania Business Council Executive President Sunny Sun held talks at the Poly Art Museum in Beijing with Chen Peng, General Manager, and Xie Rui, Deputy General Manager, of Poly Art Education Investment Co., Ltd.

The two sides held in-depth discussions on deepening China-Australia cultural and arts cooperation and reached consensus on a number of points. The central topic was jointly planning and staging the 2026 Spring Festival Gala in Sydney, Australia, with the aim of developing it into a high-level flagship event that promotes mutual cultural exchange between China and Australia. In addition, the two sides plan to expand cooperation in Melbourne in the future across a range of formats, including art exhibitions, educational study tours and youth exchanges, building a regular network for cultural exchange.

The meeting marked a key step forward in the two sides' practical cooperation in the cultural and arts field and laid a solid foundation for advancing a series of cultural projects in the future.$obci$,
  array['culture-arts']::text[], null, 'published', '2025-12-11T10:00:00+11:00'::timestamptz, false, null, null
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();

-- china-agricultural-university-wafi-cooperation (source: docs/support docs/V2/农业大学(1).docx)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'china-agricultural-university-wafi-cooperation',
  (select id from public.news_categories where slug = 'association-news'),
  $obci$深化农食合作 共促健康未来：大洋洲工商业委员会与中国农业大学共商WaFi平台合作新篇章$obci$, $obci$Deepening Agri-Food Cooperation for a Healthy Future: Oceania Business Council and China Agricultural University Discuss a New Chapter of WaFi Platform Cooperation$obci$,
  $obci$12月11日，大洋洲工商业委员会执行会长孙国照率代表团访问中国农业大学，与WaFi平台总策划付文阁教授举行工作会谈。双方就委员会参与2026年3月WaFi平台活动、争取主办“澳大利亚（大洋洲）专场”、推动WaFi大洋洲办事处落户墨尔本，以及中国农业大学MBA代表团2026年11月赴澳考察等事项达成初步共识。$obci$, $obci$On 11 December, Oceania Business Council Executive President Sunny Sun led a delegation to China Agricultural University for talks with Professor Fu Wenge, chief planner of the WaFi platform. They reached preliminary consensus on the Council joining WaFi events in March 2026, a proposed Australia (Oceania) session and Melbourne office, and an MBA delegation visiting Australia in November 2026.$obci$,
  $obci$12月11日，继成功访问北京保利艺术博物馆后，大洋洲工商业委员会执行会长、澳大利亚内蒙古总商会创会会长孙国照率代表团一行，前往中国农业大学，与该校院长、WaFi平台总策划付文阁教授举行深度工作会谈。双方聚焦农业食品与大健康产业，围绕国际平台共建、活动联动、产业融合等议题展开务实交流，共同擘画中澳在相关领域互利合作的新蓝图。

会谈在富有建设性的氛围中进行。付文阁院长首先对孙国照会长一行的到访表示欢迎，并系统介绍了WaFi平台的定位与发展愿景。WaFi作为一个高规格的国际交流与展示平台，旨在汇聚全球智慧与资源，推动农业、食品与大健康产业的创新融合与可持续发展，其顾问委员会成员包括前农业部部长等权威人士，平台秉持“农食一体，药食同源”的先进理念，致力于构建全球产业协同网络。

孙国照会长详细阐述了大洋洲工商业委员会在促进澳中乃至大洋洲地区与中国经贸文化交流中所扮演的桥梁角色。他特别表达了对WaFi平台理念与价值的高度认同，并代表委员会正式提出强烈意愿，希望争取成为WaFi平台“澳大利亚（大洋洲）专场”的主要主办方之一。孙会长表示，委员会将全力利用其在地资源优势，积极推介并组织澳大拉西亚地区优质的农业科技、绿色食品、健康产品及相关企业参与WaFi平台活动，同时积极推动WaFi大洋洲办事处的建立，提议以澳大利亚文化经济重镇墨尔本作为基地，以便更高效、更常态化的服务区域合作与资源对接。

双方就一系列具体合作事项达成重要共识与初步规划：

- **平台深度参与：**大洋洲工商业委员会将积极组织参与2026年3月举办的WaFi平台重要活动，并力争在活动中呈现具有大洋洲特色的专题内容，展示该地区在农业与食品健康领域的技术成果与产业优势。
- **双向考察联动：**作为回访与深度对接，中国农业大学MBA项目师生及关联企业代表团计划于2026年11月赴澳大利亚，参与当地重要的大健康产业展会，并同步开展为期10天左右的商务考察与交流活动。此举旨在让中国产业界与学界精英深入澳洲本土，实地了解市场、对接技术、探索合作。
- **理念与实践融合：**双方一致同意，将共同倡导与践行“农食一体，药食同源”的理念，通过WaFi等平台，推动从田间到餐桌、从农产品到健康品的全产业链合作，促进中澳在高端农业、功能食品、健康管理等领域的产学研协同创新。

此次会谈成果丰硕，标志着大洋洲工商业委员会与中国农业大学的合作从意向沟通迈入了具体规划与项目推进的新阶段。双方一致认为，农业与健康是关乎民生的永恒产业，也是中澳互补优势显著、合作潜力巨大的重点领域。最终，双方共同展望，愿以此次会晤为起点，携手共促中澳友谊，推动两国在经贸、人文、教育等方面的共同发展，特别是通过WaFi这样的高端平台，将两国的产业优势、科技资源与市场潜力紧密结合，为全球农食健康产业的可持续发展贡献“中澳方案”。

随着合作蓝图的徐徐展开，大洋洲工商业委员会与中国农业大学的此次战略携手，不仅为WaFi平台的国际化、区域化运作注入了强劲动力，也为中澳在农业与大健康这一关键领域的务实合作搭建了专业化、机制化的新桥梁，必将为两国企业和人民带来更多实实在在的福祉与发展机遇。$obci$,
  $obci$On 11 December, following a successful visit to the Poly Art Museum in Beijing, Sunny Sun, Executive President of the Oceania Business Council and Founding President of the Australia Inner Mongolia General Chamber of Commerce, led a delegation to China Agricultural University for in-depth working talks with Professor Fu Wenge, Dean at the university and chief planner of the WaFi platform. Focusing on the agri-food and health industries, the two sides held practical discussions on jointly building an international platform, linking events and integrating industries, and together outlined a new blueprint for mutually beneficial China-Australia cooperation in these fields.

The talks took place in a constructive atmosphere. Dean Fu Wenge first welcomed President Sunny Sun and his delegation and gave a systematic introduction to the positioning and development vision of the WaFi platform. As a high-level international exchange and exhibition platform, WaFi aims to bring together global expertise and resources to drive innovative integration and sustainable development across the agriculture, food and health industries. Its advisory committee includes authoritative figures such as a former Minister of Agriculture, and the platform upholds the forward-looking concept of "agriculture and food as one, with medicine and food sharing the same origin", dedicating itself to building a global network of industry collaboration.

President Sunny Sun explained in detail the bridging role that the Oceania Business Council plays in promoting economic, trade and cultural exchanges between Australia, and the wider Oceania region, and China. He expressed strong agreement with the concept and values of the WaFi platform and, on behalf of the Council, formally conveyed a strong wish to become one of the principal hosts of a WaFi "Australia (Oceania) Session". President Sun said the Council would make full use of its local resources to actively promote and organise the participation of high-quality agricultural technology, green food and health product enterprises from Australasia in WaFi platform events, and would actively promote the establishment of a WaFi Oceania office, proposing Melbourne, a major cultural and economic centre of Australia, as its base so as to serve regional cooperation and resource matching more efficiently and on a regular basis.

The two sides reached important consensus and preliminary plans on a series of specific cooperation matters:

- **In-depth platform participation:** The Oceania Business Council will actively organise participation in the major WaFi platform event to be held in March 2026 and will strive to present themed content with distinctive Oceania characteristics, showcasing the region's technological achievements and industrial strengths in agriculture, food and health.
- **Two-way study visits:** As a return visit and deeper engagement, a delegation of faculty and students from the China Agricultural University MBA programme, together with representatives of affiliated enterprises, plans to travel to Australia in November 2026 to attend a major local health industry exhibition and to carry out business study and exchange activities of around 10 days. The aim is to bring leading figures from Chinese industry and academia into Australia to understand the market first-hand, connect with technology and explore cooperation.
- **Integrating concept and practice:** The two sides agreed to jointly advocate and put into practice the concept of "agriculture and food as one, with medicine and food sharing the same origin", using WaFi and other platforms to promote whole-industry-chain cooperation from field to table and from agricultural products to health products, and to foster industry-academia-research collaborative innovation between China and Australia in high-end agriculture, functional foods and health management.

The talks were highly productive and mark the transition of cooperation between the Oceania Business Council and China Agricultural University from an exchange of intentions to a new stage of concrete planning and project implementation. Both sides agreed that agriculture and health are enduring industries that concern people's livelihoods, and are also priority fields in which China and Australia enjoy clear complementary strengths and great potential for cooperation. Looking ahead, both sides expressed the hope that this meeting would serve as a starting point for jointly advancing China-Australia friendship and promoting the shared development of the two countries in trade, people-to-people exchange and education, and in particular for closely combining the industrial strengths, scientific resources and market potential of both countries through high-level platforms such as WaFi, contributing a "China-Australia solution" to the sustainable development of the global agri-food and health industry.

As the blueprint for cooperation gradually unfolds, this strategic partnership between the Oceania Business Council and China Agricultural University not only injects strong momentum into the international and regional operation of the WaFi platform, but also builds a new professional and institutionalised bridge for practical China-Australia cooperation in the key fields of agriculture and health, and will surely bring more tangible benefits and development opportunities to the enterprises and people of both countries.$obci$,
  array['health']::text[], null, 'published', '2025-12-11T15:00:00+11:00'::timestamptz, false, null, null
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();

-- lishui-pharma-conference-ccpit-agreement (source: docs/support docs/V2/新闻提炼(1).docx)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'lishui-pharma-conference-ccpit-agreement',
  (select id from public.news_categories where slug = 'association-news'),
  $obci$大洋洲工商业委员会率团参加第十九届成长型医药企业发展大会 与丽水市贸促会签署战略合作协议$obci$, $obci$Oceania Business Council Leads Delegation to the 19th Growth-Stage Pharmaceutical Enterprises Development Conference and Signs Strategic Cooperation Agreement with Lishui CCPIT$obci$,
  $obci$2025年11月23日，第十九届成长型医药企业发展大会在浙江丽水开幕，大洋洲工商业委员会会长孙国照率团参会并展示马努卡蜂蜜等健康产品。会议期间，委员会与丽水市贸促会签署战略合作协议，达成邀请丽水医药企业参加2026年墨尔本澳中健康产业博览会、在青田进口商品城设立大洋洲馆、考察丽水本地医药企业三项合作。$obci$, $obci$On 23 November 2025 the Oceania Business Council, led by President Sunny Sun, attended the 19th Growth-Stage Pharmaceutical Enterprises Development Conference in Lishui, Zhejiang, and signed a strategic cooperation agreement with Lishui CCPIT covering the 2026 Australia-China Health Industry Expo in Melbourne, an Oceania pavilion in Qingtian and visits to local pharmaceutical enterprises.$obci$,
  $obci$2025年11月23日，第十九届成长型医药企业发展大会在浙江丽水开幕。澳大利亚大洋洲工商业委员会会长孙国照率团参会，展示马努卡蜂蜜等健康产品，并与丽水市政府开展交流。

会议期间，委员会与丽水市贸促会签署战略合作协议，建立长期合作关系。双方达成三项合作：一是邀请丽水医药企业组团参加2026年10月在墨尔本举办的澳中健康产业博览会，丽水市将提供出海补助；二是推动在青田进口商品城设立大洋洲馆，引进澳大利亚产品；三是代表团实地考察丽水本地医药企业，促进产业对接。

此次合作为两地医药健康产业搭建了双向贸易与交流平台。$obci$,
  $obci$On 23 November 2025, the 19th Growth-Stage Pharmaceutical Enterprises Development Conference opened in Lishui, Zhejiang. Sunny Sun, President of the Oceania Business Council of Australia, led a delegation to the conference, showcased health products such as manuka honey, and held exchanges with the Lishui Municipal Government.

During the conference, the Council signed a strategic cooperation agreement with the Lishui Council for the Promotion of International Trade (CCPIT), establishing a long-term cooperative relationship. The two sides agreed on three areas of cooperation: first, inviting Lishui pharmaceutical enterprises to attend as a group the Australia-China Health Industry Expo to be held in Melbourne in October 2026, with Lishui providing subsidies for going overseas; second, promoting the establishment of an Oceania Pavilion at the Qingtian Imported Commodities City to bring in Australian products; and third, arranging for the delegation to visit local pharmaceutical enterprises in Lishui on site to promote industry matchmaking.

This cooperation has built a platform for two-way trade and exchange between the pharmaceutical and health industries of the two regions.$obci$,
  array['health']::text[], null, 'published', '2025-11-23T12:00:00+11:00'::timestamptz, false, null, null
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();

-- ningxia-ccpit-melbourne-business-matching (source: docs/support docs/V2/双向奔赴，共拓蓝海｜中澳商务对接交流会圆满落幕(1).docx)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'ningxia-ccpit-melbourne-business-matching',
  (select id from public.news_categories where slug = 'events-coverage'),
  $obci$双向奔赴，共拓蓝海｜中澳商务对接交流会圆满落幕$obci$, $obci$Mutual Engagement, Shared Horizons | China–Australia Business Matching Meeting Concludes Successfully$obci$,
  $obci$大洋洲工商业委员会与宁夏贸易促进委员会在墨尔本 Hexa Space 联合主办中澳商务对接交流会。活动设政企致辞、产业分享、企业推介与自由洽谈等环节，宁夏十余家标杆企业参与推介，覆盖葡萄酒、特色农食、供应链贸易与企业营销等领域；双方正式签署战略合作备忘录，建立长期战略合作伙伴关系。$obci$, $obci$The Oceania Business Council and the Ningxia Council for the Promotion of International Trade co-hosted a China–Australia business matching meeting at Hexa Space in Melbourne. Government and business guests, local companies and more than ten Ningxia enterprises took part in speeches, industry sharing, company presentations and networking; the two organisations signed a memorandum of understanding establishing a long-term partnership.$obci$,
  $obci$近日，由**大洋洲工商业委员会**与**宁夏贸易促进委员会**联合主办的中澳商务对接交流会，在墨尔本Hexa Space顺利落幕。活动汇聚澳洲政府嘉宾、本土优质企业及宁夏特色产业代表团，以产业对话、品牌展示、战略签约为核心，搭建起宁澳经贸互通、资源对接、长效合作的国际化平台，为两地企业务实合作、产业出海赋能蓄力。

本次活动摒弃形式化交流，聚焦**精准对接、务实共赢、长效赋能**，通过政企致辞、产业分享、企业推介、战略合作签约、自由洽谈多个核心环节，高效打通宁夏特色产业出海通道，精准链接澳洲市场、技术与渠道资源，实现两地优势互补、双向发展。

## 大咖致辞定调 锚定中澳合作新方向

两位核心嘉宾的致辞，为两地经贸合作明确了务实深耕、长期共建的发展基调，勾勒出宁澳产业协同的清晰路径。

### 大洋洲工商业委员会：搭建中澳双向经贸桥梁

大洋洲工商业委员会执行会长孙国照先生发表开场致辞。他表示，中澳经贸互补性突出，澳洲拥有成熟的国际市场与商业体系，宁夏坐拥葡萄酒、特色农产品、大健康食品等优质特色产业，是中国西北对外开放的重要窗口。

他强调，本次对接会是两地**常态化、机制化合作的全新起点**。未来委员会将持续发挥海外平台优势，全方位助力宁夏企业深耕澳洲市场、打造国际品牌，同时引入澳洲优质资源落地宁夏，构建双向奔赴的经贸合作生态。

### 宁夏贸促会：携特色产业开拓澳洲国际市场

宁夏贸易促进委员会会长梁万荣先生重点推介了宁夏核心特色产业，聚焦**贺兰山东麓葡萄酒、枸杞农产品、绿色食品加工、大健康产业**等优势赛道，介绍了宁夏产业的生态优势与品质竞争力。

梁会长表示，澳洲是宁夏企业出海布局的核心重点市场。此次率本土头部企业代表团赴澳，旨在主动对接澳洲高端市场、先进技术与成熟贸易渠道。他期待两地建立常态化沟通机制，在贸易互通、品牌共建、市场开拓等领域深化务实合作，让宁夏优质特色产品扎根澳洲、走向国际。

## 中澳双向对话 激活产业合作新势能

本次活动集结宁夏十余标杆企业，覆盖葡萄酒、特色农食、供应链贸易、企业营销等核心领域。银色高地、留世、沃尔丰酒庄及杞里香、厚生记、百事恒兴等知名品牌，集中展示宁夏特色产品与产业实力，凭借优质品质获得澳洲政企嘉宾广泛认可，充分展现了宁夏特色产业的国际竞争力与发展潜力。

澳洲本土企业代表积极响应、精准对接，形成高效双向互动格局。

Hexa Group六合集团CEO William Yang先生结合澳洲本土运营经验分享核心观点，提出跨境合作的关键在于**本土适配、落地运营、长效发展**。作为本次活动场地支持方，六合集团深耕墨尔本本土市场，熟悉当地商业规则与消费需求。未来将持续依托场地、商圈与运营资源，为中澳企业对接洽谈、项目落地、品牌推广提供一站式支撑，助力宁夏品牌快速适配澳洲市场，解决出海落地难题。

大洋洲工商业委员会商业服务分会秘书长赵松亮，聚焦跨境商务服务、合规运营、资源整合，剖析宁澳合作机遇与痛点，为宁夏企业出海提供专业、可落地的实操指导，打通两地商业服务协同通道。

佰德芙酒庄负责人王岭梅，结合澳洲葡萄酒产业发展经验，分享国际酒庄运营、品牌出海、产区联动的成熟模式，为宁夏葡萄酒产业对标国际标准、优化产品体系、开拓海外市场提供了宝贵参考。

## 数字电商赋能 打通企业出海新通道

为助力宁夏传统产业数字化出海，活动特邀澳洲数字技术、跨境电商领域资深从业者分享实战经验，破解传统外贸渠道窄、效率低、对接难等问题，为企业国际化转型赋能。

Digitec IT Solutions总监Flex Huo聚焦数字化跨境运营、海外品牌线上推广，分享适配中小企业的出海方案，提出依托数字技术搭建线上跨境销售矩阵，助力宁夏产品精准触达澳洲终端市场。

Fureeze创始人Alex Xiao结合澳洲电商规则与消费特点，详解跨境电商流量运营、渠道布局实操路径。他表示，宁夏优质农食、红酒产品高度契合澳洲高端消费需求，借助成熟电商模式可快速打开增量市场。

同时，BERRINGA百龄佳创始人Peter Woodward、澳醇思慕集团董事总经理潘雪飞，分别分享澳洲大健康、高端食品产业的市场布局与合作模式，为宁澳多产业融合发展拓宽了合作边界。

## 战略签约落地 开启长期共赢新格局

活动现场，大洋洲工商业委员会与宁夏贸易促进委员会正式签署**战略合作备忘录（MOU）**，标志着两地正式建立长期稳定的战略合作伙伴关系。

本次签约是两地常态化深度合作的重要里程碑。未来双方将聚焦产业对接、品牌出海、技术交流、贸易互通、人才联动等核心领域，持续搭建专业化商务对接平台，推动宁夏特色产业规模化出海，助力澳洲优质资源落地宁夏，实现双向赋能、互利共赢。

## 结语

本次中澳商务对接交流会，实现了宁夏特色产业国际化突破与澳洲本土资源本土化赋能的深度融合。以政企联动为依托，以产业互补为核心，以数字出海为抓手，成功打通中澳经贸合作壁垒。

未来，双方将持续深耕务实合作、搭建长效交流平台，助力更多宁夏优质企业扬帆出海，让塞上特色产业立足澳洲、走向世界，持续释放中澳经贸合作新活力！$obci$,
  $obci$Recently, the China–Australia Business Matching Meeting, co-hosted by the **Oceania Business Council** and the **Ningxia Council for the Promotion of International Trade**, concluded successfully at Hexa Space in Melbourne. The event brought together Australian government guests, leading local enterprises and a delegation representing Ningxia's signature industries. Centred on industry dialogue, brand showcases and the signing of a strategic agreement, it established an international platform for Ningxia–Australia economic and trade connectivity, resource matching and long-term cooperation, building momentum for practical cooperation between enterprises of the two regions and for their industries to go global.

Moving beyond formalities, the event focused on **precise matching, practical win-win outcomes and long-term empowerment**. Through several core segments, including speeches by government and business leaders, industry sharing, company presentations, the signing of a strategic cooperation agreement and open networking, it efficiently opened channels for Ningxia's signature industries to go global, connected them precisely with Australian market, technology and channel resources, and promoted complementary strengths and two-way development between the two regions.

## Keynote Speeches Set the Tone and Chart a New Direction for China–Australia Cooperation

The speeches by the two principal guests set a tone of practical, in-depth and long-term joint development for economic and trade cooperation between the two regions, and outlined a clear path for Ningxia–Australia industrial collaboration.

### Oceania Business Council: Building a Two-Way Economic and Trade Bridge between China and Australia

Mr Sunny Sun, Executive President of the Oceania Business Council, delivered the opening address. He noted that China and Australia are highly complementary in economic and trade terms: Australia has a mature international market and business system, while Ningxia is home to high-quality signature industries such as wine, specialty agricultural products and health foods, and is an important window for the opening-up of north-west China.

He stressed that this matching meeting is **a new starting point for regular, institutionalised cooperation** between the two regions. Going forward, the Council will continue to leverage its strengths as an overseas platform to help Ningxia enterprises cultivate the Australian market and build international brands in every respect, while also bringing high-quality Australian resources to Ningxia, creating an economic and trade cooperation ecosystem in which both sides reach out to each other.

### CCPIT Ningxia: Taking Signature Industries to the Australian and International Markets

Mr Liang Wanrong, President of the Ningxia Council for the Promotion of International Trade, gave a focused presentation of Ningxia's core signature industries, highlighting advantageous sectors such as **wine from the eastern foothills of the Helan Mountains, goji berries and other agricultural products, green food processing and the health industry**, and introduced the ecological advantages and quality competitiveness of Ningxia's industries.

President Liang said that Australia is a core priority market for Ningxia enterprises going global. The purpose of leading a delegation of top local enterprises to Australia was to proactively connect with Australia's high-end market, advanced technology and mature trade channels. He expressed the hope that the two regions would establish a regular communication mechanism and deepen practical cooperation in areas such as trade connectivity, joint brand building and market development, so that Ningxia's high-quality signature products can take root in Australia and reach the world.

## Two-Way China–Australia Dialogue Unlocks New Momentum for Industrial Cooperation

The event assembled more than ten leading Ningxia enterprises covering core sectors including wine, specialty agricultural and food products, supply-chain trade and corporate marketing. Well-known brands such as the Silver Heights, Legacy Peak and Woerfeng wineries, together with Qilixiang, Houshengji and Baishi Hengxing, showcased Ningxia's signature products and industrial strength. Their high quality won broad recognition from Australian government and business guests, fully demonstrating the international competitiveness and development potential of Ningxia's signature industries.

Representatives of Australian local enterprises responded actively and engaged in precise matching, forming an efficient pattern of two-way interaction.

Mr William Yang, CEO of Hexa Group, shared his core views drawing on his experience of local operations in Australia, proposing that the keys to cross-border cooperation are **local adaptation, on-the-ground operations and long-term development**. As the venue partner for the event, Hexa Group has deep roots in the Melbourne market and is familiar with local business rules and consumer needs. Going forward, it will continue to draw on its venue, business-district and operational resources to provide one-stop support for China–Australia business matching and negotiations, project landing and brand promotion, helping Ningxia brands adapt quickly to the Australian market and overcome the practical challenges of establishing themselves overseas.

Zhao Songliang, Secretary-General of the Business Services Chapter of the Oceania Business Council, focused on cross-border business services, compliant operations and resource integration, analysing the opportunities and pain points of Ningxia–Australia cooperation and offering Ningxia enterprises professional, actionable guidance for going global, thereby opening a channel for business-services collaboration between the two regions.

Wang Lingmei, head of Baidefu Winery, drew on the development experience of the Australian wine industry to share proven models of international winery operations, brand internationalisation and regional collaboration, providing valuable reference for Ningxia's wine industry as it benchmarks against international standards, optimises its product portfolio and develops overseas markets.

## Digital E-commerce Empowerment Opens New Channels for Enterprises Going Global

To help Ningxia's traditional industries go global through digital channels, the event invited experienced Australian practitioners in digital technology and cross-border e-commerce to share hands-on experience, addressing the narrow channels, low efficiency and matching difficulties of traditional foreign trade and empowering the international transformation of enterprises.

Flex Huo, Director of Digitec IT Solutions, focused on digital cross-border operations and online promotion of overseas brands, sharing go-global solutions suited to small and medium-sized enterprises and proposing the use of digital technology to build an online cross-border sales matrix that helps Ningxia products reach Australian end consumers precisely.

Alex Xiao, founder of Fureeze, drew on Australian e-commerce rules and consumer characteristics to explain in detail the practical paths for cross-border e-commerce traffic operations and channel deployment. He said that Ningxia's high-quality agricultural, food and wine products closely match Australia's high-end consumer demand, and that mature e-commerce models can quickly open up incremental markets.

In addition, Peter Woodward, founder of BERRINGA, and Pan Xuefei, Managing Director of Aochun Simu Group, respectively shared the market positioning and cooperation models of Australia's health and premium food industries, broadening the boundaries of cooperation for multi-industry integrated development between Ningxia and Australia.

## Strategic Agreement Signed, Opening a New Chapter of Long-Term Win-Win Cooperation

At the event, the Oceania Business Council and the Ningxia Council for the Promotion of International Trade formally signed a **strategic cooperation memorandum of understanding (MOU)**, marking the formal establishment of a long-term and stable strategic partnership between the two regions.

The signing is an important milestone in regular, in-depth cooperation between the two regions. Going forward, the two parties will focus on core areas including industry matching, brand internationalisation, technology exchange, trade connectivity and talent exchange, continue to build a professional business matching platform, promote the large-scale internationalisation of Ningxia's signature industries and help high-quality Australian resources land in Ningxia, achieving two-way empowerment and mutual benefit.

## Conclusion

This China–Australia Business Matching Meeting achieved a deep integration of the international breakthrough of Ningxia's signature industries with the local empowerment of Australian resources. Relying on government–business collaboration, centred on industrial complementarity and driven by digital internationalisation, it successfully broke down barriers to China–Australia economic and trade cooperation.

Going forward, the two parties will continue to deepen practical cooperation and build a long-term exchange platform, helping more high-quality Ningxia enterprises set sail overseas so that Ningxia's signature industries can establish themselves in Australia and reach the world, continuously unleashing new vitality in China–Australia economic and trade cooperation.$obci$,
  array['business-services']::text[], null, 'published', '2026-09-10T09:00:00+10:00'::timestamptz, false, null, null
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();

-- oceania-business-council-2026-agm-melbourne (source: docs/support docs/V2/大洋洲商会新闻(1).docx)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'oceania-business-council-2026-agm-melbourne',
  (select id from public.news_categories where slug = 'association-news'),
  $obci$聚势谋远 共谱新篇 —— 大洋洲工商业委员会（OBC）2026年度会员大会盛大召开$obci$, $obci$Gathering Strength, Charting the Future: Oceania Business Council (OBC) Holds Its 2026 Annual General Meeting$obci$,
  $obci$2026年5月1日，大洋洲工商业委员会在墨尔本世界贸易中心举行年度会员大会，逾百名中澳政商嘉宾出席。会长Hon. Bruce Atkinson AM致开幕辞，执行会长孙国照作年度工作报告；大会为教育、建筑、地产、高端人才与博士创新、商业服务及堪培拉六大分会授牌，公布新一届秘书处名单，并颁发议员、分会及秘书处证书。$obci$, $obci$On 1 May 2026 the Oceania Business Council held its 2026 Annual General Meeting at the World Trade Centre Melbourne with more than one hundred guests from Australia and China. President Hon. Bruce Atkinson AM opened the meeting, Executive President Sunny Sun delivered the annual report, six new committees were inaugurated, and the new secretariat was announced.$obci$,
  $obci$5月1日星期五，暮春时节的墨尔本生机盎然。在地标性建筑——墨尔本世界贸易中心（WTC），一场汇聚政商精英的盛会如期而至。澳大利亚大洋洲工商业委员会（Oceania Business Council, OBC）在此隆重举行2026年度会员大会。本次大会以“承前启后，活力绽放”为主题，不仅是对过去一年辉煌战绩的全面检阅，更是对未来战略转型与全球化布局的深度擘画。

![2026年度会员大会现场](/news-media/oceania-business-council-2026-agm-melbourne/01.jpg)

大会现场精英云集，高朋满座。来自中澳两国的政要、企业家、行业领袖及各界贤达逾百人出席。VIP嘉宾：Cr Gladys Liu，Mr. Simon Qian OAM，Mr. Arthur Wu，Mr. Bill Long，Mr. Nick Yan，Mr. Jerry Zhu，Hon. Ken Smith AM，Hon. Bruce Atkinson AM等，共同见证了OBC从传统商协会向“国际资源整合平台”华丽转身的里程碑时刻。

![大会现场](/news-media/oceania-business-council-2026-agm-melbourne/02.jpg)

## 高屋建瓴：核心领导层亮相与组织架构革新

大会伊始，OBC会长、Hon. Bruce Atkinson AM（维多利亚州立法议会前议长）发表了热情洋溢的开幕致辞。他高度评价了委员会在过去一年中在跨文化沟通与经贸桥梁搭建方面所做的努力，并对新一年的战略规划提出了殷切期望。

![大会开幕致辞](/news-media/oceania-business-council-2026-agm-melbourne/03.jpg)

随后，Hon. Ken Smith AM（OBC荣誉主席、创会会长）登台发言。作为OBC的缔造者，Smith先生深情回顾了委员会的创立初心，并对当前取得的体系化成果表示欣慰。大会上举行了庄重的证书颁发仪式：Hon. Ken Smith AM 为 Hon. Bruce Atkinson AM 颁发“理事会荣誉主席”证书，以表彰其在推动州际及国际事务中的卓越领导力；同时，Hon. Bruce Atkinson AM 亦为 Hon. Ken Smith AM 颁发议员证书，肯定其作为精神领袖对组织的深远影响。

![证书颁发仪式](/news-media/oceania-business-council-2026-agm-melbourne/04.jpg)

![证书颁发仪式](/news-media/oceania-business-council-2026-agm-melbourne/05.jpg)

执行会长孙国照（Sunny Sun） 代表理事会作了题为《战略转型与全球链接》的年度工作报告。他系统回顾了OBC在组织建设、国际合作及项目落地方面的突破性进展，特别是与七家机构联合发起成立“澳大利亚国际创业创新联盟”的重大举措，标志着OBC正式完成了从OBAI到OBC的品牌升级与战略重塑。

![执行会长孙国照（Sunny Sun）作年度工作报告](/news-media/oceania-business-council-2026-agm-melbourne/06.jpg)

## 重磅发布：六大专业分会正式成立

为适应日益精细化的市场需求，大会迎来了核心亮点环节——六大新分会授牌仪式。这标志着OBC的专业化服务能力迈上了新台阶：

### 教育分会 (Education Committee)

秘书长 Yang Li 李扬。该分会旨在搭建中澳教育资源互通的立交桥，促进留学、职业教育与学术交流。

![教育分会授牌](/news-media/oceania-business-council-2026-agm-melbourne/07.jpg)

### 建筑分会 (Construction Committee)

秘书长 Bryan Guan 关星明，常务副秘书长 Steven Yeung。聚焦中澳基建合作、绿色建筑标准互认及技术输出。

![建筑分会授牌](/news-media/oceania-business-council-2026-agm-melbourne/08.jpg)

![建筑分会授牌](/news-media/oceania-business-council-2026-agm-melbourne/09.jpg)

### 地产分会 (Real Estate Committee)

秘书长 Diana Chen。致力于整合澳洲地产开发与投资资源，为中国资本合规出海提供专业指引。

![地产分会授牌](/news-media/oceania-business-council-2026-agm-melbourne/10.jpg)

### 高端人才与博士创新分会 (High-Level Talent & Doctoral Innovation Committee)

秘书长 Arina Tang 唐彩焱。这是OBC最具科技含量的板块，旨在汇聚高层次人才，推动产学研一体化转化。

### 商业服务分会 (Business Services Committee)

秘书长 Albert Zhao 赵松亮。为企业提供法律、税务、会计及市场咨询的一站式解决方案。

![商业服务分会授牌](/news-media/oceania-business-council-2026-agm-melbourne/11.jpg)

### 堪培拉分会 (Canberra Branch)

秘书长 Ding Ding 丁玎。作为连接联邦政府核心圈层的触角，强化在首都特区的政策沟通与资源对接。

![堪培拉分会授牌](/news-media/oceania-business-council-2026-agm-melbourne/12.jpg)

## 秘书处与新锐力量

大会宣布了新一届秘书处核心成员名单：秘书长 Sheryl Leigh，副秘书长 Jing Liu 刘京、Maggie Zhang 张金淼、Jessica Xu 徐冰心。他们的加入为OBC注入了年轻化、专业化的管理血液。

### 商会议员证书颁发

Angela Liu 刘芷均

![Angela Liu 刘芷均 · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/13.jpg)

Georgia Qiao 乔亚楠

![Georgia Qiao 乔亚楠 · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/14.jpg)

Bryan Guan 关星明

![Bryan Guan 关星明 · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/15.jpg)

Joanne Chen

![Joanne Chen · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/16.jpg)

Steven Kakoliris

![Steven Kakoliris · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/17.jpg)

Jing Liu 刘京

![Jing Liu 刘京 · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/18.jpg)

Sheryl Leigh

![Sheryl Leigh · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/19.jpg)

Diana Chen

![Diana Chen · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/20.jpg)

Yang Li 李杨

![Yang Li 李杨 · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/21.jpg)

Albert Zhao 赵松亮

![Albert Zhao 赵松亮 · 商会议员证书](/news-media/oceania-business-council-2026-agm-melbourne/22.jpg)

- Sunny Sun 孙国照
- Frank Perre
- Diana Lin
- James Li 李俊
- Cr Gladys Liu
- Lisa Li 李霁
- Jessica Xu 徐冰心

### 分会证书颁发

教育分会 (Education Committee)

![教育分会 · 分会证书](/news-media/oceania-business-council-2026-agm-melbourne/23.jpg)

建筑分会 (Construction Committee)

![建筑分会 · 分会证书](/news-media/oceania-business-council-2026-agm-melbourne/24.jpg)

地产分会 (Real Estate Committee)

![地产分会 · 分会证书](/news-media/oceania-business-council-2026-agm-melbourne/25.jpg)

高端人才与博士创新分会 (High-Level Talent & Doctoral Innovation Committee)

![高端人才与博士创新分会 · 分会证书](/news-media/oceania-business-council-2026-agm-melbourne/26.jpg)

商业服务分会 (Business Services Committee)

![商业服务分会 · 分会证书](/news-media/oceania-business-council-2026-agm-melbourne/27.jpg)

堪培拉分会 (Canberra Branch)

![堪培拉分会 · 分会证书](/news-media/oceania-business-council-2026-agm-melbourne/28.jpg)

### 秘书处证书颁发

秘书长 Sheryl Leigh

![秘书长 Sheryl Leigh · 秘书处证书](/news-media/oceania-business-council-2026-agm-melbourne/29.jpg)

副秘书长 Jing Liu 刘京

![副秘书长 Jing Liu 刘京 · 秘书处证书](/news-media/oceania-business-council-2026-agm-melbourne/30.jpg)

副秘书长 Maggie Zhang 张金淼

![副秘书长 Maggie Zhang 张金淼 · 秘书处证书](/news-media/oceania-business-council-2026-agm-melbourne/31.jpg)

- 副秘书长 Jessica Xu 徐冰心

## 深耕细作：年度成果回顾与双向交流机制

在随后的会议议程中，秘书长 Sheryl Leigh 详细阐述了2026年委员会年度工作计划。她强调，OBC将不再局限于简单的牵线搭桥，而是转向“深水区”运作，构建实质性的双向交流平台和长效机制。

### 对华合作：从“签约”走向“落地”

执行会长孙国照在汇报中指出，OBC在过去一年中实现了对华合作的体系化布局。委员会已与中国浙江、江苏、安徽、上海、云南、广东、内蒙古等多个省市建立了深度战略合作机制，并与各地贸促会、商务局及行业协会建立了直通渠道。目前，合作重心已从早期的协议签署阶段，全面迈入常态化对接与实质性项目推进的新阶段。

### 标杆项目：闪耀国际舞台

会议重点展示了两项年度标杆成果：一是OBC组织会员企业参加中国全国性医药行业博览会，并成功设立“大洋洲馆”，集中展示澳洲优质大健康产品，为中国市场开拓铺平道路；二是2025年10月在墨尔本成功举办的“澳中大健康产业博览会”暨“世界传统医药论坛”。该盛会吸引了全球400余家中国企业参展及150多位专家学者与会，极大地提升了OBC的国际声誉，并促成了海量商业配对。

![大会现场](/news-media/oceania-business-council-2026-agm-melbourne/32.jpg)

### 项目落地：打造中澳经贸核心载体

备受瞩目的苏州吴中区“大洋洲产业园”项目在大会上再次被提及。目前该项目已取得战略合作共识，正稳步推进，未来将成为中澳双向投资与贸易的物理载体与核心枢纽。此外，围绕企业实际需求，OBC已建立起涵盖TGA认证、市场准入、仓储物流及本地推广的全链条服务体系，切实帮助会员企业实现商业价值闭环。

## 展望未来：构建有执行力的国际合作组织

站在新的历史起点，OBC对未来发展提出了更高远的愿景。2026年，委员会将继续秉持“链接大洋洲，服务全世界”的使命，重点做好三件事：一是扩大“朋友圈”，加速国际合作网络向亚太及其他地区延伸；二是跑出“加速度”，全力推动大洋洲产业园等重点项目从图纸变为现实；三是提供“高价值”，依托六大专业分会，为会员提供更具针对性的精准服务。

OBC正逐步成长为一个“有资源、有平台、有项目、有执行力”的新型国际组织。正如执行会长孙国照所言：“我们不仅是一个商会，更是一个生态系统。”

## 致谢与闭幕

大会尾声，特别鸣谢对委员会做出重大贡献的 Hon. Ken Smith AM 先生，正是他的远见卓识奠定了OBC的基石。同时，衷心感谢 Cr Gladys Liu、Mr. Simon Qian OAM、Mr. Arthur Wu、Mr. Bill Long、Mr. Nick Yan、Mr. Jerry Zhu 以及洪门民治党主委伍颂达、上海商会会长钱恒裕等各界领导长期以来给予OBC的鼎力支持。

![大会嘉宾合影](/news-media/oceania-business-council-2026-agm-melbourne/33.jpg)

最后，在世界贸易中心（WTC）代表的精彩推介后，伴随着悠扬的音乐与热烈的交谈，2026年度会员大会在温馨而充满活力的商务交流酒会中圆满落幕。这不仅是一场总结过往的盛会，更是一个凝聚共识、携手共赢的新开端。大洋洲工商业委员会正蓄势待发，准备在国际舞台上绽放更加夺目的光彩。$obci$,
  $obci$On Friday 1 May, Melbourne was brimming with vitality in the late-spring season. At the landmark World Trade Centre Melbourne (WTC), a gathering of political and business leaders took place as scheduled: the Oceania Business Council (OBC) of Australia held its 2026 Annual General Meeting there in grand style. Under the theme "Building on the Past, Bursting with Vitality", the meeting was not only a comprehensive review of the outstanding achievements of the past year, but also an in-depth blueprint for future strategic transformation and global expansion.

![The 2026 Annual General Meeting](/news-media/oceania-business-council-2026-agm-melbourne/01.jpg)

The venue was filled with distinguished guests. More than one hundred political figures, entrepreneurs, industry leaders and prominent members of the community from China and Australia attended. VIP guests including Cr Gladys Liu, Mr. Simon Qian OAM, Mr. Arthur Wu, Mr. Bill Long, Mr. Nick Yan, Mr. Jerry Zhu, Hon. Ken Smith AM and Hon. Bruce Atkinson AM jointly witnessed this milestone moment as the Oceania Business Council transformed from a traditional business association into an "international resource integration platform".

![The meeting in session](/news-media/oceania-business-council-2026-agm-melbourne/02.jpg)

## A Commanding Vision: The Core Leadership Takes the Stage and the Organisation Is Restructured

At the opening of the meeting, Hon. Bruce Atkinson AM, President of the Oceania Business Council and former President of the Legislative Council of Victoria, delivered a warm opening address. He spoke highly of the Council's efforts over the past year in cross-cultural communication and in building bridges for economic and trade cooperation, and expressed high expectations for the strategic plan for the year ahead.

![Opening address](/news-media/oceania-business-council-2026-agm-melbourne/03.jpg)

Hon. Ken Smith AM, Honorary Chairman and Founding President of the Oceania Business Council, then took the stage. As the founder of the Council, Mr. Smith looked back with deep feeling on the original aspirations behind its establishment and expressed his satisfaction with the systematic results achieved to date. A solemn certificate presentation ceremony was held at the meeting: Hon. Ken Smith AM presented Hon. Bruce Atkinson AM with the certificate of "Honorary Chairman of the Board" in recognition of his outstanding leadership in advancing interstate and international affairs; at the same time, Hon. Bruce Atkinson AM presented Hon. Ken Smith AM with a councillor certificate, acknowledging his profound influence on the organisation as its spiritual leader.

![Certificate presentation ceremony](/news-media/oceania-business-council-2026-agm-melbourne/04.jpg)

![Certificate presentation ceremony](/news-media/oceania-business-council-2026-agm-melbourne/05.jpg)

Executive President Sunny Sun delivered the annual work report, entitled "Strategic Transformation and Global Connectivity", on behalf of the Board. He systematically reviewed the Council's breakthroughs in organisational development, international cooperation and project implementation, in particular the major initiative of co-founding the "Australian International Entrepreneurship and Innovation Alliance" together with seven institutions, which marked the formal completion of the Council's brand upgrade and strategic reshaping from OBAI to OBC.

![Executive President Sunny Sun delivers the annual work report](/news-media/oceania-business-council-2026-agm-melbourne/06.jpg)

## Major Announcement: Six Professional Committees Formally Established

To meet increasingly specialised market demands, the meeting reached its core highlight: the inauguration ceremony of six new committees. This marked a new level in the Council's professional service capability:

### Education Committee

Secretary-General Yang Li. The committee aims to build an interchange for the exchange of educational resources between China and Australia, and to promote international study, vocational education and academic exchange.

![Inauguration of the Education Committee](/news-media/oceania-business-council-2026-agm-melbourne/07.jpg)

### Construction Committee

Secretary-General Bryan Guan; Executive Deputy Secretary-General Steven Yeung. The committee focuses on Australia-China infrastructure cooperation, mutual recognition of green building standards and technology export.

![Inauguration of the Construction Committee](/news-media/oceania-business-council-2026-agm-melbourne/08.jpg)

![Inauguration of the Construction Committee](/news-media/oceania-business-council-2026-agm-melbourne/09.jpg)

### Real Estate Committee

Secretary-General Diana Chen. The committee is dedicated to integrating Australian property development and investment resources, and to providing professional guidance for Chinese capital going overseas in compliance with regulations.

![Inauguration of the Real Estate Committee](/news-media/oceania-business-council-2026-agm-melbourne/10.jpg)

### High-Level Talent & Doctoral Innovation Committee

Secretary-General Arina Tang. This is the Council's most technology-intensive segment, aiming to bring together high-level talent and to promote the integrated transformation of research into industry.

### Business Services Committee

Secretary-General Albert Zhao. The committee provides enterprises with one-stop solutions covering legal, tax, accounting and market consulting services.

![Inauguration of the Business Services Committee](/news-media/oceania-business-council-2026-agm-melbourne/11.jpg)

### Canberra Branch

Secretary-General Ding Ding. Serving as the Council's antenna into the core circles of the federal government, the branch strengthens policy communication and resource matching in the Australian Capital Territory.

![Inauguration of the Canberra Branch](/news-media/oceania-business-council-2026-agm-melbourne/12.jpg)

## The Secretariat and New Talent

The meeting announced the core members of the new secretariat: Secretary-General Sheryl Leigh, and Deputy Secretaries-General Jing Liu, Maggie Zhang and Jessica Xu. Their arrival injects younger, more professional management talent into the Council.

### Presentation of Councillor Certificates

Angela Liu

![Angela Liu · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/13.jpg)

Georgia Qiao

![Georgia Qiao · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/14.jpg)

Bryan Guan

![Bryan Guan · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/15.jpg)

Joanne Chen

![Joanne Chen · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/16.jpg)

Steven Kakoliris

![Steven Kakoliris · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/17.jpg)

Jing Liu

![Jing Liu · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/18.jpg)

Sheryl Leigh

![Sheryl Leigh · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/19.jpg)

Diana Chen

![Diana Chen · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/20.jpg)

Yang Li

![Yang Li · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/21.jpg)

Albert Zhao

![Albert Zhao · councillor certificate](/news-media/oceania-business-council-2026-agm-melbourne/22.jpg)

- Sunny Sun
- Frank Perre
- Diana Lin
- James Li
- Cr Gladys Liu
- Lisa Li
- Jessica Xu

### Presentation of Committee Certificates

Education Committee

![Education Committee · committee certificate](/news-media/oceania-business-council-2026-agm-melbourne/23.jpg)

Construction Committee

![Construction Committee · committee certificate](/news-media/oceania-business-council-2026-agm-melbourne/24.jpg)

Real Estate Committee

![Real Estate Committee · committee certificate](/news-media/oceania-business-council-2026-agm-melbourne/25.jpg)

High-Level Talent & Doctoral Innovation Committee

![High-Level Talent & Doctoral Innovation Committee · committee certificate](/news-media/oceania-business-council-2026-agm-melbourne/26.jpg)

Business Services Committee

![Business Services Committee · committee certificate](/news-media/oceania-business-council-2026-agm-melbourne/27.jpg)

Canberra Branch

![Canberra Branch · committee certificate](/news-media/oceania-business-council-2026-agm-melbourne/28.jpg)

### Presentation of Secretariat Certificates

Secretary-General Sheryl Leigh

![Secretary-General Sheryl Leigh · secretariat certificate](/news-media/oceania-business-council-2026-agm-melbourne/29.jpg)

Deputy Secretary-General Jing Liu

![Deputy Secretary-General Jing Liu · secretariat certificate](/news-media/oceania-business-council-2026-agm-melbourne/30.jpg)

Deputy Secretary-General Maggie Zhang

![Deputy Secretary-General Maggie Zhang · secretariat certificate](/news-media/oceania-business-council-2026-agm-melbourne/31.jpg)

- Deputy Secretary-General Jessica Xu

## Steady Cultivation: Review of the Year's Achievements and Two-Way Exchange Mechanisms

In the subsequent agenda, Secretary-General Sheryl Leigh elaborated on the Council's annual work plan for 2026. She stressed that the Council will no longer confine itself to simple matchmaking, but will move into "deep-water" operations, building substantive two-way exchange platforms and long-term mechanisms.

### Cooperation with China: From "Signing" to "Implementation"

In his report, Executive President Sunny Sun pointed out that over the past year the Council has achieved a systematic framework for cooperation with China. The Council has established in-depth strategic cooperation mechanisms with a number of Chinese provinces and municipalities, including Zhejiang, Jiangsu, Anhui, Shanghai, Yunnan, Guangdong and Inner Mongolia, and has opened direct channels with local Councils for the Promotion of International Trade (CCPIT), commerce bureaus and industry associations. The focus of cooperation has now moved fully beyond the early stage of signing agreements into a new stage of regular engagement and the advancement of substantive projects.

### Flagship Projects: Shining on the International Stage

The meeting highlighted two flagship achievements of the year. First, the Council organised member enterprises to take part in a national pharmaceutical industry expo in China and successfully set up an "Oceania Pavilion" showcasing premium Australian health products, paving the way for the development of the Chinese market. Second, the "Australia-China Health Industry Expo" and the "World Traditional Medicine Forum" were successfully held in Melbourne in October 2025. The event attracted more than 400 Chinese enterprises from around the world as exhibitors and over 150 experts and scholars as participants, greatly enhancing the Council's international reputation and generating a large volume of business matchmaking.

![The meeting in session](/news-media/oceania-business-council-2026-agm-melbourne/32.jpg)

### Project Implementation: Building a Core Vehicle for Australia-China Trade

The much-anticipated "Oceania Industrial Park" project in Wuzhong District, Suzhou, was mentioned again at the meeting. The project has reached a consensus on strategic cooperation and is progressing steadily; in the future it will become the physical vehicle and core hub for two-way investment and trade between China and Australia. In addition, in response to the practical needs of enterprises, the Council has built a full-chain service system covering TGA certification, market access, warehousing and logistics, and local promotion, effectively helping member enterprises close the loop on commercial value.

## Looking Ahead: Building an International Cooperation Organisation with the Capacity to Deliver

Standing at a new historical starting point, the Council has set out a loftier vision for its future development. In 2026, the Council will continue to uphold its mission of "Connecting Oceania, Serving the World" and will focus on three priorities: first, expanding its "circle of friends" by accelerating the extension of its international cooperation network into the Asia-Pacific and other regions; second, "picking up speed" by pushing key projects such as the Oceania Industrial Park from blueprint to reality; and third, delivering "high value" by relying on the six professional committees to provide members with more targeted and precise services.

The Council is steadily growing into a new type of international organisation "with resources, a platform, projects and the capacity to deliver". As Executive President Sunny Sun put it: "We are not only a chamber of commerce, but an ecosystem."

## Acknowledgements and Closing

As the meeting drew to a close, special thanks were extended to Hon. Ken Smith AM for his major contributions to the Council; it was his foresight that laid the cornerstone of the Oceania Business Council. Heartfelt thanks also went to Cr Gladys Liu, Mr. Simon Qian OAM, Mr. Arthur Wu, Mr. Bill Long, Mr. Nick Yan and Mr. Jerry Zhu, as well as to Wu Songda, Chairman of the Hongmen Minzhi Party, Qian Hengyu, President of the Shanghai Chamber of Commerce, and other leaders from all walks of life for the strong support they have long given to the Council.

![Group photograph of guests at the meeting](/news-media/oceania-business-council-2026-agm-melbourne/33.jpg)

Finally, following an engaging presentation by a representative of the World Trade Centre (WTC), the 2026 Annual General Meeting drew to a successful close with a warm and lively business networking reception, amid pleasant music and animated conversation. It was not only an occasion to review the past, but also a new beginning for building consensus and pursuing shared success. The Oceania Business Council is poised and ready to shine even more brightly on the international stage.$obci$,
  '{}'::text[], '/news-media/oceania-business-council-2026-agm-melbourne/cover.jpg', 'published', '2026-05-27T23:00:00+00:00'::timestamptz, true, null, null
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();

-- shanghai-changning-visit-ai-manufacturing (source: docs/support docs/V2/大洋洲商会代表团长宁行：咖啡机器人、智慧港口与战略合作共绘合作新蓝图(1).docx)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'shanghai-changning-visit-ai-manufacturing',
  (select id from public.news_categories where slug = 'association-news'),
  $obci$大洋洲商会代表团长宁行：咖啡机器人、智慧港口与战略合作共绘合作新蓝图$obci$, $obci$Oceania Business Council Delegation Visits Changning: Coffee Robots, Smart Ports and a Strategic Agreement Draw a New Blueprint for Cooperation$obci$,
  $obci$12月13日，大洋洲工商业委员会孙国照会长率代表团到访上海长宁区，参观氦豚机器人科技有限公司的咖啡机器人，了解WELLOCEAN的人工智能港口解决方案，并与长宁区科委签署战略合作协议，双方将在人工智能、高端制造等领域建立常态化交流机制。$obci$, $obci$On 13 December, an Oceania Business Council delegation led by President Sunny Sun visited Shanghai's Changning District, touring the coffee robots of Helium Dolphin Robotics, learning about WELLOCEAN's AI port solution, and signing a strategic cooperation agreement with the Changning District Science and Technology Commission covering AI and advanced manufacturing.$obci$,
  $obci$一杯由机器人冲泡的咖啡，一场围绕科技与未来的对话，大洋洲与中国商贸合作在上海长宁区写下新的注脚。

12月13日，大洋洲工商业委员会代表团孙国照会长一行到访上海长宁区，展开了一场科技与创新的深度体验。代表团参观了氦豚机器人科技有限公司的咖啡机器人、了解WELLOCEAN的全局化人工智能港口解决方案，并与长宁区科委签署战略合作协议。

这场访问展现了中国在人工智能与高端制造领域的最新成果，也为大洋洲与中国企业的合作开辟了新路径。

## 咖啡机器人：一杯饮品的科技革命

在氦豚机器人科技有限公司，代表团目睹了如何通过人工智能技术重新定义咖啡体验。COFE+第6代全智能·咖啡机器人展示了其卓越能力：50秒完成一杯现磨咖啡，单日产能突破1000杯。

![COFE+ 咖啡机器人现场制作的咖啡，奶泡上 3D 打印的图案](/news-media/shanghai-changning-visit-ai-manufacturing/01.jpg)

这款机器人不仅速度惊人，更具备大师级拉花技艺和3D打印功能，能将企业Logo、照片甚至游客笑脸瞬间印制在咖啡奶泡上。代表团成员品尝了由机器人制作的咖啡，对其精准的口感和艺术性表示赞叹。

氦豚科技作为全球饮品机器人领域的领军企业，拥有100多项国际专利，其产品已通过美国FDA、欧盟CE等全球权威认证。COFE+已成功进入全球50多个发达国家，覆盖中国15个省市，落地场景包括景区、商场、高校、医院等上千类点位。这种轻资产、高效率、高毛利的模式为餐饮行业提供了全新解决方案。

## 智慧港口：人工智能赋能全球贸易

代表团随后来到WELLOCEAN，WELLOCEAN代表向代表团介绍，该系统是“全球首套多功能人工智能远控岸桥识别系统”，具备地面识别方式、多功能同步实时识别以及全时段、全天候高识别准确率等特点。

![WELLOCEAN 智慧港口解决方案展示](/news-media/shanghai-changning-visit-ai-manufacturing/02.jpg)

物联网技术联通“人、车、箱、船、机、场”六大要素，使提送箱在港作业时间缩短26.2%，远洋干线船舶在泊船时效率提升28%。系统串联起码头多台岸桥、场桥和人工智能运输车，涵盖多个人工智能算法和数个智能模块。运输车在北斗导航系统指引下到达智能解锁站，然后沿着大数据计算的最佳行驶路线把货物运到指定位置。相信未来的合作领域将会更加的广阔。

## 战略签约：构建长期合作机制

参观结束后，大洋洲工商业委员会代表团与上海长宁区科委代表周开悦共同出席了在PoBe德必产业园举行的战略合作协议签署仪式。长宁区作为上海开发开放早、国际化程度高的区域，始终致力于为企业提供高效便捷的服务。此次与大洋洲工商业委员会的合作，是长宁区践行“相聚上海 共创未来”全球宣介活动精神的又一具体举措。

![大洋洲工商业委员会与上海长宁区科委战略合作协议签署仪式](/news-media/shanghai-changning-visit-ai-manufacturing/03.jpg)

这一合作框架将建立常态化交流机制，推动大洋洲企业与长宁区在人工智能、高端制造等领域的深度合作。合作内容涵盖技术交流、人才培训、项目对接等多个层面。

## 合作前景：大洋洲与中国企业的共赢之路

大洋洲工商业委员会代表团此次长宁之行，为双方未来的合作奠定了坚实基础。随着全球竞争格局重塑，企业出海不再只是“走出去”，而是以技术为底座、以合规为战略的系统工程。

大洋洲企业可以借助长宁区的平台优势，更好地进入中国市场；中国企业也可以通过这一通道，拓展大洋洲市场。随着战略合作协议的签署，上海市区长宁区与大洋洲企业的合作将进入新阶段。$obci$,
  $obci$A cup of coffee brewed by a robot and a conversation about technology and the future: in Shanghai's Changning District, business cooperation between Oceania and China gained a new chapter.

On 13 December, an Oceania Business Council delegation led by President Sunny Sun visited Changning District, Shanghai, for an in-depth experience of technology and innovation. The delegation toured the coffee robots of Helium Dolphin Robotics Technology Co., Ltd., learned about WELLOCEAN's holistic artificial intelligence port solution, and signed a strategic cooperation agreement with the Changning District Science and Technology Commission.

The visit showcased China's latest achievements in artificial intelligence and advanced manufacturing, and opened new avenues for cooperation between Oceanian and Chinese enterprises.

## Coffee Robots: A Technological Revolution in a Single Cup

At Helium Dolphin Robotics Technology Co., Ltd., the delegation saw how artificial intelligence is redefining the coffee experience. The sixth-generation COFE+ fully intelligent coffee robot demonstrated its capabilities: a freshly ground cup of coffee in 50 seconds, with a daily output exceeding 1,000 cups.

![Coffee made on site by the COFE+ coffee robot, with a design 3D-printed on the milk foam](/news-media/shanghai-changning-visit-ai-manufacturing/01.jpg)

The robot is not only remarkably fast but also masters latte art and 3D printing, instantly printing company logos, photographs and even visitors' smiling faces onto the milk foam. Delegation members tasted coffee made by the robot and praised its precise flavour and artistry.

As a leading global company in beverage robotics, Helium Dolphin holds more than 100 international patents, and its products have passed authoritative certifications worldwide, including the US FDA and EU CE. COFE+ has entered more than 50 developed countries around the world and covers 15 provinces and municipalities in China, deployed at over a thousand types of locations including scenic areas, shopping malls, universities and hospitals. This asset-light, high-efficiency, high-margin model offers the food and beverage industry an entirely new solution.

## Smart Ports: Artificial Intelligence Empowering Global Trade

The delegation then visited WELLOCEAN, where a WELLOCEAN representative explained that the system is "the world's first multifunctional AI remote-controlled quay crane recognition system", featuring ground-based recognition, synchronous real-time multifunctional recognition, and high recognition accuracy around the clock in all weather conditions.

![Display of WELLOCEAN's smart-port solution](/news-media/shanghai-changning-visit-ai-manufacturing/02.jpg)

Internet of Things technology links the six elements of "people, vehicles, containers, ships, machinery and yards", cutting container pick-up and delivery time at port by 26.2% and raising the berth efficiency of ocean-going mainline vessels by 28%. The system connects multiple quay cranes, yard cranes and AI transport vehicles at the terminal, incorporating a number of AI algorithms and several intelligent modules. Guided by the BeiDou navigation system, the transport vehicles travel to intelligent unlocking stations and then carry the cargo to its designated position along the optimal route calculated from big data. It is believed that the scope for future cooperation will be even broader.

## Strategic Signing: Building a Long-Term Cooperation Mechanism

After the tours, the Oceania Business Council delegation and Zhou Kaiyue, representative of the Shanghai Changning District Science and Technology Commission, attended the signing ceremony for a strategic cooperation agreement held at the PoBe DoBe Industrial Park. As one of the earliest areas of Shanghai to open up and one of its most internationalised, Changning District has always been committed to providing efficient and convenient services for enterprises. This cooperation with the Oceania Business Council is another concrete step by Changning District in carrying forward the spirit of the "Meet in Shanghai, Create the Future Together" global promotion campaign.

![Signing ceremony for the strategic cooperation agreement between the Oceania Business Council and the Shanghai Changning District Science and Technology Commission](/news-media/shanghai-changning-visit-ai-manufacturing/03.jpg)

This cooperation framework will establish a regular exchange mechanism and promote in-depth cooperation between Oceanian enterprises and Changning District in fields such as artificial intelligence and advanced manufacturing. The cooperation covers multiple areas, including technology exchange, talent training and project matchmaking.

## Cooperation Outlook: A Win-Win Path for Oceanian and Chinese Enterprises

The Oceania Business Council delegation's visit to Changning has laid a solid foundation for future cooperation between the two sides. As the global competitive landscape is reshaped, going overseas is no longer simply about "going out"; it is a systematic undertaking built on technology and guided by a compliance strategy.

Oceanian enterprises can draw on Changning District's platform advantages to enter the Chinese market more effectively, while Chinese enterprises can use this channel to expand into the Oceanian market. With the signing of the strategic cooperation agreement, cooperation between Shanghai's Changning District and Oceanian enterprises will enter a new stage.$obci$,
  array['tech-innovation']::text[], '/news-media/shanghai-changning-visit-ai-manufacturing/cover.jpg', 'published', '2025-12-13T12:00:00+11:00'::timestamptz, false, null, null
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();

-- shanghai-nanhongqiao-chamber-visit (source: docs/support docs/V2/大洋洲工商业委员会代表团访问上海南虹桥商会 共拓国际合作新空间(1).doc)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'shanghai-nanhongqiao-chamber-visit',
  (select id from public.news_categories where slug = 'association-news'),
  $obci$大洋洲工商业委员会代表团访问上海南虹桥商会 共拓国际合作新空间$obci$, $obci$Oceania Business Council Delegation Visits Shanghai Nanhongqiao Chamber of Commerce to Explore New Space for International Cooperation$obci$,
  $obci$2025年12月5日，大洋洲工商业委员会执行会长孙国照一行到访上海，与南虹桥商会举行交流会议，新虹街道办事处副书记周行君出席。南虹桥商会介绍了其发展定位、组织架构、会员情况及企业出海服务举措；孙国照另与上海内蒙古商会执行会长方铭贤会晤，商讨中澳医疗康养合作。双方表示将建立长期交流互访机制。$obci$, $obci$On 5 December 2025 an Oceania Business Council delegation led by Executive President Sunny Sun met the Nanhongqiao Chamber of Commerce in Shanghai, which presented its positioning, membership and going-global services; Sun also met the Shanghai Inner Mongolia Chamber of Commerce on health cooperation. The two chambers said they would establish long-term exchange and reciprocal-visit mechanisms.$obci$,
  $obci$一次深入的交流，一杯香醇的咖啡，为大洋洲与中国企业合作开辟了新路径。

2025年12月5日，大洋洲工商业委员会代表团孙国照会长一行到访上海，与南虹桥商会举行友好交流会议，上海市闵行区人民政府新虹街道办事处副书记周行君出席会议。南虹桥商会外联部李晓详细介绍了其发展定位、组织架构、会员情况以及赋能企业出海的举措，双方共同探讨了未来互利合作方向。此次访问进一步加强了大洋洲工商业委员会与中国商协会机构的联系，为促进大洋洲与中国的经贸往来搭建了新平台。

![大洋洲工商业委员会代表团一行到访南虹桥商会](/news-media/shanghai-nanhongqiao-chamber-visit/01.jpg)

## 南虹桥商会：国际化商会的能级跃升

南虹桥商会在交流中全面展示了其作为国际化商会的全新定位。今年4月，该商会完成了能级提升的重要变革，更名为“南虹桥商会”，并扩大了会员规模，优化了组织架构。

商会会员有147家知名企业，形成了更加开放、包容和国际化的商会氛围。在组织架构上，商会设立了出海服务联盟和青年创业者联谊会，构建了“政治引领承载体、社会治理联合体、建设发展共同体”三位一体的组织体系。

![交流会上介绍的南虹桥商会会员情况](/news-media/shanghai-nanhongqiao-chamber-visit/02.jpg)

## 全方位服务体系：助力企业全球发展

南虹桥商会构建了多元化的会员服务体系，尤其在赋能企业出海方面提供了有力支持。商会依托虹桥国际中央商务区的区位优势和政策优势，为企业搭建完善的出海服务平台。

出海服务联盟作为开放、共享、协同的服务平台，整合多方资源，为企业提供包括跨境财税规划、海外上市辅导等专业化服务。

商会还定期举办“企业出海”系列主题活动，组织会员企业参访成功出海企业，学习品牌全球化经验。这些活动为会员企业搭建了深度交流平台，共同探寻在数字化运营、海外市场拓展等方面的合作机遇。

![交流会议现场](/news-media/shanghai-nanhongqiao-chamber-visit/03.jpg)

## 咖啡文化：商务交流的独特纽带

在本次交流活动中，初心咖啡负责人张泽华成为双方沟通的独特桥梁。咖啡文化作为一种跨语种、跨国界的共识载体，在商务交流中发挥着越来越重要的作用。

南虹桥商会所在的虹桥国际中央商务区核心区，正在打造更加开放包容的国际营商环境。咖啡文化交流正是这种国际化氛围的体现。

![交流现场的咖啡杯，杯套印有「抵达上海的第一杯」](/news-media/shanghai-nanhongqiao-chamber-visit/04.jpg)

## 上海内蒙古商会：蒙澳携手共筑健康桥梁

上海内蒙古商会执行会长方铭贤与大洋洲工商业委员会执行会长、澳大利亚内蒙古总商会创会会长孙国照在上海举行会晤。双方围绕中澳医疗康养产业合作、资源共享等议题进行了深入交流。

双方一致同意建立常态化交流机制，未来将依托澳中健康产业博览会等平台，推动内蒙古康养资源与国际市场对接，深化在医疗、康养等领域的务实合作。

## 共赢未来：拓展大洋洲与中国合作空间

本次交流为双方未来合作奠定了坚实基础。大洋洲工商业委员会孙国照会长一行作为推动大洋洲国家与中国经贸合作的非营利性组织，其核心目标是响应“一带一路”倡议，推动大洋洲国家与中国的经贸往来。

交流结束后，双方代表均表示将建立长期交流互访机制。南虹桥商会将组织企业家代表团回访大洋洲，实地考察澳大利亚和新西兰的市场环境与合作机遇。

大洋洲工商业委员会也计划在未来一年内组织更多大洋洲企业访问上海，利用虹桥国际中央商务区的平台优势，进一步拓展中国市场。$obci$,
  $obci$An in-depth exchange and a cup of fragrant coffee opened up a new path for cooperation between enterprises in Oceania and China.

On 5 December 2025, a delegation of the Oceania Business Council led by President Sunny Sun visited Shanghai and held a friendly exchange meeting with the Nanhongqiao Chamber of Commerce. Zhou Xingjun, Deputy Party Secretary of the Xinhong Sub-district Office of the People's Government of Minhang District, Shanghai, attended the meeting. Li Xiao of the External Relations Department of the Nanhongqiao Chamber of Commerce gave a detailed introduction to the chamber's development positioning, organisational structure, membership and measures to empower enterprises going global, and the two sides jointly explored directions for future mutually beneficial cooperation. The visit further strengthened the Oceania Business Council's ties with Chinese chambers of commerce and business associations and built a new platform for promoting economic and trade exchanges between Oceania and China.

![The Oceania Business Council delegation arriving at the Nanhongqiao Chamber of Commerce](/news-media/shanghai-nanhongqiao-chamber-visit/01.jpg)

## Nanhongqiao Chamber of Commerce: An International Chamber Steps Up a Level

During the exchange, the Nanhongqiao Chamber of Commerce gave a full presentation of its new positioning as an international chamber of commerce. In April this year, the chamber completed a major transformation to raise its standing, was renamed the "Nanhongqiao Chamber of Commerce", expanded its membership and optimised its organisational structure.

The chamber's members comprise 147 well-known enterprises, creating a more open, inclusive and international chamber atmosphere. In terms of organisational structure, the chamber has established a Going-Global Service Alliance and a Young Entrepreneurs Association, building a three-in-one organisational system of "a carrier of political leadership, a union for social governance and a community for construction and development".

![The chamber's membership presented at the meeting](/news-media/shanghai-nanhongqiao-chamber-visit/02.jpg)

## A Comprehensive Service System: Supporting Enterprises' Global Development

The Nanhongqiao Chamber of Commerce has built a diversified member service system, providing strong support in particular for empowering enterprises going global. Drawing on the locational and policy advantages of the Hongqiao International Central Business District, the chamber has built a comprehensive going-global service platform for enterprises.

As an open, shared and collaborative service platform, the Going-Global Service Alliance integrates resources from many parties to provide enterprises with professional services including cross-border tax and financial planning and guidance on overseas listings.

The chamber also regularly holds a series of themed "Enterprises Going Global" events, organising member enterprises to visit companies that have successfully gone global and learn from their experience in taking brands international. These events give member enterprises a platform for in-depth exchange, jointly exploring cooperation opportunities in areas such as digital operations and overseas market expansion.

![The exchange meeting in progress](/news-media/shanghai-nanhongqiao-chamber-visit/03.jpg)

## Coffee Culture: A Unique Bond in Business Exchange

During this exchange, Zhang Zehua, head of Chuxin Coffee, became a unique bridge for communication between the two sides. Coffee culture, as a shared medium that crosses languages and borders, is playing an increasingly important role in business exchange.

The core area of the Hongqiao International Central Business District, where the Nanhongqiao Chamber of Commerce is located, is building a more open and inclusive international business environment. The exchange of coffee culture is an embodiment of this international atmosphere.

![A coffee cup at the meeting, its sleeve printed with "the first cup on arriving in Shanghai"](/news-media/shanghai-nanhongqiao-chamber-visit/04.jpg)

## Shanghai Inner Mongolia Chamber of Commerce: Inner Mongolia and Australia Join Hands to Build a Health Bridge

Fang Mingxian, Executive President of the Shanghai Inner Mongolia Chamber of Commerce, met in Shanghai with Sunny Sun, Executive President of the Oceania Business Council and founding President of the Australia Inner Mongolia General Chamber of Commerce. The two sides held in-depth exchanges on topics including China–Australia cooperation in the medical and health and wellness industries and the sharing of resources.

The two sides agreed to establish a regular exchange mechanism and, in future, to draw on platforms such as the Australia–China Health Industry Expo to connect Inner Mongolia's health and wellness resources with international markets and deepen practical cooperation in fields such as medical care and health and wellness.

## A Win-Win Future: Expanding the Space for Cooperation Between Oceania and China

This exchange laid a solid foundation for future cooperation between the two sides. The Oceania Business Council, represented by President Sunny Sun and his delegation, is a non-profit organisation that promotes economic and trade cooperation between the countries of Oceania and China; its core objective is to respond to the Belt and Road Initiative and promote economic and trade exchanges between the countries of Oceania and China.

After the exchange, representatives of both sides said they would establish a long-term mechanism for exchanges and reciprocal visits. The Nanhongqiao Chamber of Commerce will organise a delegation of entrepreneurs to pay a return visit to Oceania to examine first-hand the market environment and cooperation opportunities in Australia and New Zealand.

The Oceania Business Council also plans to organise more Oceania enterprises to visit Shanghai within the coming year, using the platform advantages of the Hongqiao International Central Business District to further expand into the Chinese market.$obci$,
  '{}'::text[], '/news-media/shanghai-nanhongqiao-chamber-visit/cover.jpg', 'published', '2025-12-05T12:00:00+11:00'::timestamptz, false, null, null
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();

-- tcm-health-industry-promotion-mid-year-reception-2025 (source: https://www.acd.com.au/chinese-community-news/dayangzhougongshangyeweiyuanhuijuxingzhongyiyaodajiankangchanyetuijianhuijigongshanghuinianzhongjiuhui/)
insert into public.news (slug, category_id, title_zh, title_en, summary_zh, summary_en, body_zh, body_en, tags, cover_image_path, status, published_at, is_featured, author_name, source_url)
values (
  'tcm-health-industry-promotion-mid-year-reception-2025',
  (select id from public.news_categories where slug = 'events-coverage'),
  $obci$中医药大健康产业推荐会暨工商会年中酒会在墨尔本世贸中心举行$obci$, $obci$TCM and Health Industry Promotion Meeting and Mid-Year Reception Held at World Trade Centre Melbourne$obci$,
  $obci$2025年8月8日，大洋洲工商业委员会在墨尔本世贸中心举行中医药大健康产业推荐会暨工商会年中酒会，澳中各界200余位嘉宾出席。会上通报了代表团访华成果、苏州大洋洲产业园及10月澳中健康产品博览会的筹备情况；维州议会前上议长Bruce Atkinson当选新任会长，新一届理事会成立，新办公室揭牌。$obci$, $obci$On 8 August 2025 the Oceania Business Council held its TCM and Health Industry Promotion Meeting and mid-year reception at World Trade Centre Melbourne with more than 200 guests. Reports covered the China delegation, the Suzhou Oceania Industrial Park and the October Australia–China Health Products Expo; Bruce Atkinson was elected President and a new council was formed.$obci$,
  $obci$2025年8月8日，大洋洲工商业委员会在墨尔本世贸中心举行中医药大健康产业推荐会暨工商会年中酒会，澳中各界200余位嘉宾出席。会长Ken Smith回顾了近期工作，介绍了会员赴苏州参展的机会及委员会向新西兰、斐济、库克群岛、基里巴斯、瑙鲁、巴布亚新几内亚、萨摩亚、所罗门群岛、汤加、图瓦卢、瓦努阿图等大洋洲国家拓展的计划。

执行会长Sunny Sun通报了代表团访华情况、苏州大洋洲产业园概况，以及10月26日至27日将在墨尔本举办的澳中健康产品博览会与世界传统医药论坛的筹备情况。皇家儿童医院基金会介绍了“Fly for the Kids”项目。

维州议会前上议长Bruce Atkinson当选委员会新任会长；新一届理事会成立并颁发证书，并聘任荣誉顾问；委员会新办公室揭牌，博览会组委会同日宣布成立。$obci$,
  $obci$On 8 August 2025 the Oceania Business Council held its TCM and Health Industry Promotion Meeting and mid-year reception at World Trade Centre Melbourne, attended by more than 200 guests from the Australian and Chinese communities. President Ken Smith reviewed the council's recent work, noted an opportunity for members to exhibit in Suzhou, and outlined the council's expansion to other Oceania countries, including New Zealand, Fiji, the Cook Islands, Kiribati, Nauru, Papua New Guinea, Samoa, the Solomon Islands, Tonga, Tuvalu and Vanuatu.

Executive President Sunny Sun reported on the delegation's visit to China, an overview of the Oceania Industrial Park in Suzhou, and preparations for the Australia–China Health Products Expo and the World Traditional Medicine Forum, to be held in Melbourne on 26–27 October 2025. The Royal Children's Hospital Foundation presented its "Fly for the Kids" project.

Former President of the Victorian Legislative Council Bruce Atkinson was elected the council's new President. A new council was formed, with certificates presented and honorary advisers appointed; the council's new office was unveiled, and the expo organising committee was announced on the same day.$obci$,
  array['health']::text[], null, 'published', '2025-08-08T18:00:00+10:00'::timestamptz, false, null, $obci$https://www.acd.com.au/chinese-community-news/dayangzhougongshangyeweiyuanhuijuxingzhongyiyaodajiankangchanyetuijianhuijigongshanghuinianzhongjiuhui/$obci$
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_zh = excluded.title_zh, title_en = excluded.title_en,
  summary_zh = excluded.summary_zh, summary_en = excluded.summary_en,
  body_zh = excluded.body_zh, body_en = excluded.body_en,
  tags = excluded.tags,
  cover_image_path = coalesce(excluded.cover_image_path, public.news.cover_image_path),
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  author_name = excluded.author_name,
  source_url = excluded.source_url,
  updated_at = now();
